version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-container
    pull_policy: never
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswordspring.sql.init.mode=always
      MYSQL_DATABASE: appointment_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data: